<?php

namespace Database\Factories;

use App\Models\Kendaraan;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Kendaraan>
 */
class KendaraanFactory extends Factory
{
    /**
     * 24 unit armada tetap (angkutan orang & alat berat/hauling) untuk seeder.
     *
     * @var array<int, array<string, mixed>>
     */
    public const FLEET = [
        [
            'nomor_polisi' => 'KT 1001 AB',
            'merk' => 'Toyota',
            'tipe' => 'Hilux Double Cabin',
            'tahun' => 2022,
            'warna' => 'putih',
            'jenis_kendaraan' => 'Light Vehicle (LV)',
            'kapasitas' => 5,
            'nomor_mesin' => 'ENG-LV-0001',
            'nomor_rangka' => 'FRM-LV-0001',
            'tanggal_pajak' => '2027-03-15',
            'tanggal_stnk' => '2027-03-15',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan orang. Unit milik perusahaan, operasional harian area tambang.',
            'banyak_level_persetujuan' => 2,
        ],
        [
            'nomor_polisi' => 'KT 1002 AB',
            'merk' => 'Toyota',
            'tipe' => 'Hilux Double Cabin',
            'tahun' => 2023,
            'warna' => 'putih',
            'jenis_kendaraan' => 'Light Vehicle (LV)',
            'kapasitas' => 5,
            'nomor_mesin' => 'ENG-LV-0002',
            'nomor_rangka' => 'FRM-LV-0002',
            'tanggal_pajak' => '2027-05-10',
            'tanggal_stnk' => '2027-05-10',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan orang. Unit milik perusahaan.',
            'banyak_level_persetujuan' => 2,
        ],
        [
            'nomor_polisi' => 'KT 1101 BC',
            'merk' => 'Isuzu',
            'tipe' => 'Elf NKR',
            'tahun' => 2021,
            'warna' => 'biru',
            'jenis_kendaraan' => 'Bus Karyawan',
            'kapasitas' => 30,
            'nomor_mesin' => 'ENG-BUS-0001',
            'nomor_rangka' => 'FRM-BUS-0001',
            'tanggal_pajak' => '2027-01-20',
            'tanggal_stnk' => '2027-01-20',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan orang. Bus antar-jemput karyawan shift, milik perusahaan.',
            'banyak_level_persetujuan' => 2,
        ],
        [
            'nomor_polisi' => 'KT 1102 BC',
            'merk' => 'Mitsubishi',
            'tipe' => 'Colt Diesel FE74 (Bus Body)',
            'tahun' => 2020,
            'warna' => 'biru',
            'jenis_kendaraan' => 'Bus Karyawan',
            'kapasitas' => 35,
            'nomor_mesin' => 'ENG-BUS-0002',
            'nomor_rangka' => 'FRM-BUS-0002',
            'tanggal_pajak' => '2026-12-05',
            'tanggal_stnk' => '2026-12-05',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan orang. Unit sewa dari PT Trans Angkasa Jaya, kontrak s/d Des 2027.',
            'banyak_level_persetujuan' => 2,
        ],
        [
            'nomor_polisi' => 'KT 1201 CD',
            'merk' => 'Toyota',
            'tipe' => 'Hiace Commuter',
            'tahun' => 2022,
            'warna' => 'perak',
            'jenis_kendaraan' => 'Minibus',
            'kapasitas' => 15,
            'nomor_mesin' => 'ENG-MB-0001',
            'nomor_rangka' => 'FRM-MB-0001',
            'tanggal_pajak' => '2027-02-14',
            'tanggal_stnk' => '2027-02-14',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan orang. Milik perusahaan, untuk mobilitas staf/tamu.',
            'banyak_level_persetujuan' => 2,
        ],
        [
            'nomor_polisi' => 'KT 1301 DE',
            'merk' => 'Toyota',
            'tipe' => 'Hiace Ambulance',
            'tahun' => 2019,
            'warna' => 'putih',
            'jenis_kendaraan' => 'Ambulance Tambang',
            'kapasitas' => 3,
            'nomor_mesin' => 'ENG-AMB-0001',
            'nomor_rangka' => 'FRM-AMB-0001',
            'tanggal_pajak' => '2026-11-30',
            'tanggal_stnk' => '2026-11-30',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan orang (medis + pasien). Standby klinik tambang.',
            'banyak_level_persetujuan' => 2,
        ],
        [
            'nomor_polisi' => 'KT 2001 FG',
            'merk' => 'Hino',
            'tipe' => 'FM 260 JD Dump Truck',
            'tahun' => 2021,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Dump Truck',
            'kapasitas' => 20,
            'nomor_mesin' => 'ENG-DT-0001',
            'nomor_rangka' => 'FRM-DT-0001',
            'tanggal_pajak' => '2027-04-01',
            'tanggal_stnk' => '2027-04-01',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan ton (muatan). Milik perusahaan, hauling overburden.',
            'banyak_level_persetujuan' => 3,
        ],
        [
            'nomor_polisi' => 'KT 2002 FG',
            'merk' => 'Hino',
            'tipe' => 'FM 260 JD Dump Truck',
            'tahun' => 2021,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Dump Truck',
            'kapasitas' => 20,
            'nomor_mesin' => 'ENG-DT-0002',
            'nomor_rangka' => 'FRM-DT-0002',
            'tanggal_pajak' => '2027-04-01',
            'tanggal_stnk' => '2027-04-01',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan ton (muatan). Unit sewa dari PT Sumber Alam Jaya, kontrak s/d 2028.',
            'banyak_level_persetujuan' => 3,
        ],
        [
            'nomor_polisi' => 'KT 2003 FG',
            'merk' => 'Mitsubishi',
            'tipe' => 'Fuso FN 527 Dump Truck',
            'tahun' => 2020,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Dump Truck',
            'kapasitas' => 18,
            'nomor_mesin' => 'ENG-DT-0003',
            'nomor_rangka' => 'FRM-DT-0003',
            'tanggal_pajak' => '2026-10-18',
            'tanggal_stnk' => '2026-10-18',
            'status' => 'maintenance',
            'keterangan' => 'Kapasitas dalam satuan ton (muatan). Sedang perbaikan sistem hidrolik bak.',
            'banyak_level_persetujuan' => 3,
        ],
        [
            'nomor_polisi' => 'KT 2101 GH',
            'merk' => 'Komatsu',
            'tipe' => 'HM300-5 Articulated Dump Truck',
            'tahun' => 2022,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Articulated Dump Truck (ADT)',
            'kapasitas' => 30,
            'nomor_mesin' => 'ENG-ADT-0001',
            'nomor_rangka' => 'FRM-ADT-0001',
            'tanggal_pajak' => '2027-06-25',
            'tanggal_stnk' => '2027-06-25',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan ton (muatan). Milik perusahaan, medan tambang berat.',
            'banyak_level_persetujuan' => 3,
        ],
        [
            'nomor_polisi' => 'KT 2201 HI',
            'merk' => 'Hino',
            'tipe' => 'Ranger FG 235 Fuel Truck',
            'tahun' => 2019,
            'warna' => 'merah',
            'jenis_kendaraan' => 'Fuel Truck',
            'kapasitas' => 5000,
            'nomor_mesin' => 'ENG-FT-0001',
            'nomor_rangka' => 'FRM-FT-0001',
            'tanggal_pajak' => '2026-09-12',
            'tanggal_stnk' => '2026-09-12',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan liter (tangki BBM), bukan satuan orang/ton. Milik perusahaan.',
            'banyak_level_persetujuan' => 2,
        ],
        [
            'nomor_polisi' => 'KT 2301 IJ',
            'merk' => 'Nissan',
            'tipe' => 'CWM Water Truck',
            'tahun' => 2020,
            'warna' => 'oranye',
            'jenis_kendaraan' => 'Water Truck',
            'kapasitas' => 15000,
            'nomor_mesin' => 'ENG-WT-0001',
            'nomor_rangka' => 'FRM-WT-0001',
            'tanggal_pajak' => '2026-08-22',
            'tanggal_stnk' => '2026-08-22',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan liter (tangki air, dust control). Milik perusahaan.',
            'banyak_level_persetujuan' => 2,
        ],
        [
            'nomor_polisi' => 'KT 2401 JK',
            'merk' => 'Hino',
            'tipe' => 'FM 350 Lowboy Trailer',
            'tahun' => 2018,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Lowboy Trailer',
            'kapasitas' => 40,
            'nomor_mesin' => 'ENG-LB-0001',
            'nomor_rangka' => 'FRM-LB-0001',
            'tanggal_pajak' => '2026-07-01',
            'tanggal_stnk' => '2026-07-01',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan ton (muatan alat berat). Unit sewa dari PT Cipta Logistik Tambang.',
            'banyak_level_persetujuan' => 3,
        ],
        [
            'nomor_polisi' => 'KT 2501 KL',
            'merk' => 'Mitsubishi',
            'tipe' => 'Fuso FN 517 Flatbed Truck',
            'tahun' => 2021,
            'warna' => 'biru',
            'jenis_kendaraan' => 'Flatbed Truck',
            'kapasitas' => 10,
            'nomor_mesin' => 'ENG-FB-0001',
            'nomor_rangka' => 'FRM-FB-0001',
            'tanggal_pajak' => '2027-01-08',
            'tanggal_stnk' => '2027-01-08',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan ton (muatan material/peralatan). Milik perusahaan.',
            'banyak_level_persetujuan' => 2,
        ],
        [
            'nomor_polisi' => 'KT 2601 LM',
            'merk' => 'Hino',
            'tipe' => 'FM 260 Crane Truck',
            'tahun' => 2019,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Crane Truck',
            'kapasitas' => 10,
            'nomor_mesin' => 'ENG-CR-0001',
            'nomor_rangka' => 'FRM-CR-0001',
            'tanggal_pajak' => '2026-06-15',
            'tanggal_stnk' => '2026-06-15',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan ton (kapasitas angkat crane). Milik perusahaan.',
            'banyak_level_persetujuan' => 3,
        ],
        [
            'nomor_polisi' => 'KT 2701 MN',
            'merk' => 'Komatsu',
            'tipe' => 'WA380-8 Wheel Loader',
            'tahun' => 2021,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Wheel Loader',
            'kapasitas' => 4,
            'nomor_mesin' => 'ENG-WL-0001',
            'nomor_rangka' => 'FRM-WL-0001',
            'tanggal_pajak' => '2027-02-28',
            'tanggal_stnk' => '2027-02-28',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan meter kubik bucket, milik perusahaan.',
            'banyak_level_persetujuan' => 3,
        ],
        [
            'nomor_polisi' => 'KT 2801 NO',
            'merk' => 'Caterpillar',
            'tipe' => '320D Excavator',
            'tahun' => 2020,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Excavator',
            'kapasitas' => 2,
            'nomor_mesin' => 'ENG-EX-0001',
            'nomor_rangka' => 'FRM-EX-0001',
            'tanggal_pajak' => '2026-12-20',
            'tanggal_stnk' => '2026-12-20',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan meter kubik bucket, milik perusahaan.',
            'banyak_level_persetujuan' => 3,
        ],
        [
            'nomor_polisi' => 'KT 2802 NO',
            'merk' => 'Caterpillar',
            'tipe' => '336D Excavator',
            'tahun' => 2022,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Excavator',
            'kapasitas' => 3,
            'nomor_mesin' => 'ENG-EX-0002',
            'nomor_rangka' => 'FRM-EX-0002',
            'tanggal_pajak' => '2027-03-30',
            'tanggal_stnk' => '2027-03-30',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan meter kubik bucket. Unit sewa dari PT Karya Alat Berat.',
            'banyak_level_persetujuan' => 3,
        ],
        [
            'nomor_polisi' => 'KT 2901 OP',
            'merk' => 'Komatsu',
            'tipe' => 'D65PX-18 Bulldozer',
            'tahun' => 2019,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Bulldozer',
            'kapasitas' => 0,
            'nomor_mesin' => 'ENG-BD-0001',
            'nomor_rangka' => 'FRM-BD-0001',
            'tanggal_pajak' => '2026-05-19',
            'tanggal_stnk' => '2026-05-19',
            'status' => 'aktif',
            'keterangan' => 'Kolom kapasitas tidak relevan untuk unit ini (isi 0), lihat keterangan spesifikasi terpisah.',
            'banyak_level_persetujuan' => 3,
        ],
        [
            'nomor_polisi' => 'KT 3001 PQ',
            'merk' => 'Caterpillar',
            'tipe' => '140K Motor Grader',
            'tahun' => 2020,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Motor Grader',
            'kapasitas' => 0,
            'nomor_mesin' => 'ENG-MG-0001',
            'nomor_rangka' => 'FRM-MG-0001',
            'tanggal_pajak' => '2026-09-27',
            'tanggal_stnk' => '2026-09-27',
            'status' => 'aktif',
            'keterangan' => 'Kolom kapasitas tidak relevan untuk unit ini (isi 0). Milik perusahaan, perataan jalan tambang.',
            'banyak_level_persetujuan' => 3,
        ],
        [
            'nomor_polisi' => 'KT 3101 QR',
            'merk' => 'Sakai',
            'tipe' => 'SV520 Vibro Roller',
            'tahun' => 2018,
            'warna' => 'kuning',
            'jenis_kendaraan' => 'Compactor / Vibro Roller',
            'kapasitas' => 0,
            'nomor_mesin' => 'ENG-VR-0001',
            'nomor_rangka' => 'FRM-VR-0001',
            'tanggal_pajak' => '2026-04-14',
            'tanggal_stnk' => '2026-04-14',
            'status' => 'nonaktif',
            'keterangan' => 'Kolom kapasitas tidak relevan untuk unit ini. Unit ditarik dari operasional, menunggu proses lelang/penghapusan aset.',
            'banyak_level_persetujuan' => 2,
        ],
        [
            'nomor_polisi' => 'KT 3201 RS',
            'merk' => 'Toyota',
            'tipe' => '8FD30 Forklift',
            'tahun' => 2021,
            'warna' => 'oranye',
            'jenis_kendaraan' => 'Forklift',
            'kapasitas' => 3,
            'nomor_mesin' => 'ENG-FL-0001',
            'nomor_rangka' => 'FRM-FL-0001',
            'tanggal_pajak' => '2027-07-05',
            'tanggal_stnk' => '2027-07-05',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan ton (kapasitas angkat). Milik perusahaan, operasional gudang/workshop.',
            'banyak_level_persetujuan' => 2,
        ],
        [
            'nomor_polisi' => 'KT 3301 ST',
            'merk' => 'Hino',
            'tipe' => 'FM 260 Towing Recovery',
            'tahun' => 2017,
            'warna' => 'merah',
            'jenis_kendaraan' => 'Towing/Recovery Vehicle',
            'kapasitas' => 20,
            'nomor_mesin' => 'ENG-TW-0001',
            'nomor_rangka' => 'FRM-TW-0001',
            'tanggal_pajak' => '2026-03-11',
            'tanggal_stnk' => '2026-03-11',
            'status' => 'aktif',
            'keterangan' => 'Kapasitas dalam satuan ton (kapasitas derek). Milik perusahaan, unit evakuasi kendaraan mogok/rusak.',
            'banyak_level_persetujuan' => 2,
        ],
    ];

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'nomor_polisi' => fake()->unique()->regexify('[A-Z]{1,2} [0-9]{1,4} [A-Z]{1,3}'),
            'merk' => fake()->randomElement(['Toyota', 'Honda', 'Daihatsu', 'Suzuki', 'Mitsubishi']),
            'tipe' => fake()->randomElement(['Avanza', 'Brio', 'Innova', 'Xenia', 'Pajero']),
            'tahun' => fake()->numberBetween(2010, 2024),
            'warna' => fake()->safeColorName(),
            'jenis_kendaraan' => fake()->randomElement(['Mobil', 'Minibus', 'Bus', 'Truk']),
            'kapasitas' => fake()->numberBetween(2, 40),
            'nomor_mesin' => fake()->unique()->regexify('[A-Z0-9]{12}'),
            'nomor_rangka' => fake()->unique()->regexify('[A-Z0-9]{17}'),
            'tanggal_pajak' => fake()->date(),
            'tanggal_stnk' => fake()->date(),
            'status' => 'aktif',
            'keterangan' => fake()->optional()->sentence(),
            'banyak_level_persetujuan' => 2,
        ];
    }
}
